# FarmInventory 配置文件
# 农作物仓库插件配置

# 数据库配置
database:
  # 数据库类型: h2, mysql, sqlite
  type: "h2"
  
  # H2数据库配置
  h2:
    # 数据库文件路径 (相对于插件数据文件夹)
    file: "data"
    # 用户名
    username: "sa"
    # 密码
    password: ""
    # 是否自动创建表
    auto_create_tables: true
  
  # MySQL数据库配置 (如果使用MySQL)
  mysql:
    host: "localhost"
    port: 3306
    database: "farm_inventory"
    username: "root"
    password: "password"
    # 连接池设置
    pool:
      max_connections: 10
      min_connections: 2
      connection_timeout: 30000

# 插件基本设置
settings:
  # 插件前缀
  prefix: "&b[作物仓库]"
  
  # 是否启用自动收集农作物
  auto_collect: true
  
  # 是否在玩家收获时显示提示
  show_collect_message: true
  
  # 默认仓库开关状态
  default_open: true
  
  # 最大页数限制
  max_pages:
    normal: 20
    vip: 30
    svip: 50

# 农作物配置
crops:
  # 支持的农作物类型
  enabled:
    - "POTATO"
    - "CARROT"
    - "WHEAT"
    - "WHEAT_SEEDS"
    - "BEETROOT"
    - "BEETROOT_SEEDS"
    - "NETHER_WART"
    - "PUMPKIN"
    - "MELON"
    - "SUGAR_CANE"
    - "BAMBOO"
    - "CACTUS"
  
  # 农作物显示名称
  names:
    POTATO: "马铃薯"
    CARROT: "胡萝卜"
    WHEAT: "小麦"
    WHEAT_SEEDS: "小麦种子"
    BEETROOT: "甜菜"
    BEETROOT_SEEDS: "甜菜种子"
    NETHER_WART: "地狱疣"
    PUMPKIN: "南瓜"
    MELON: "西瓜"
    SUGAR_CANE: "甘蔗"
    BAMBOO: "竹子"
    CACTUS: "仙人掌"

# GUI界面配置
gui:
  # 界面标题
  title: "&d&l桃韵斋丨作物仓库"
  
  # 每页显示物品数量
  items_per_page: 45
  
  # 界面大小 (必须是9的倍数，最大54)
  size: 54
  
  # 按钮配置
  buttons:
    back:
      slot: 45
      material: "RED_STAINED_GLASS_PANE"
      name: "&c返回菜单"
    previous_page:
      slot: 47
      material: "PAPER"
      name: "&b当前页数 {page}"
      lore:
        - "&e左键切换上页"
        - "&e右键跳转首页"
    info:
      slot: 49
      material: "{crop_material}"
      name: "&b{crop_name}"
      lore:
        - "&b仓库库存: &e{count}"
        - "&e点击取出该页作物"
    next_page:
      slot: 51
      material: "PAPER"
      name: "&b当前页数 {page}"
      lore:
        - "&e左键切换下页"
        - "&e右键快速翻页"
    close:
      slot: 53
      material: "RED_STAINED_GLASS_PANE"
      name: "&c关闭菜单"

# 消息配置
messages:
  prefix: "&b桃韵斋>>>"
  
  # 成功消息
  success:
    reload: "&a配置重载成功"
    crop_stored: "&a作物已存放仓库,打开菜单查看吧"
    crop_retrieved: "&a作物已取出"
    switch_on: "&a已开启作物仓库"
    switch_off: "&a已关闭作物仓库"
  
  # 错误消息
  error:
    no_permission: "&c你没有权限这样做"
    crop_not_found: "&c没有找到这个农作物"
    invalid_item: "&c请勿放入非作物,已返还背包"
    invalid_item_dropped: "&c请勿放入非作物,已掉落地面"
    console_only: "&c该指令只能在控制台输入"
    player_only: "&c该指令只能由玩家执行"
    unknown_command: "&c未知指令"
  
  # 信息消息
  info:
    version: "&bFarmInventory &dBy xuanming"
    papi_loaded: "&a成功载入PlaceholderAPI"
    ranmc_loaded: "&a成功载入桃韵斋"
    plugin_enabled: "&a插件已启用"
    plugin_disabled: "&a插件已卸载"

# 权限配置
permissions:
  # 基础用户权限
  user: "fm.user"
  
  # 管理员权限
  admin: "fm.admin"
  
  # VIP权限
  vip: "ranmc.vip"
  
  # SVIP权限
  svip: "ranmc.svip"

# 调试配置
debug:
  # 是否启用调试模式
  enabled: false
  
  # 是否显示详细错误信息
  show_detailed_errors: true
  
  # 是否记录数据库操作
  log_database_operations: false