name: FarmInventory
main: cc.ranmc.farm.Main
description: '桃韵斋定制农作物仓库'
author: ran
version: "4.5"
api-version: "1.21"
softdepend: [PlaceholderAPI,Ranmc]
folia-supported: true

permissions: 
  fm.user:
    default: "true"
    description: 'user only'

  fm.admin:
    default: "op"
    description: 'admin only'

commands:
  fm:
    description: fm
    usage: /<command>

  farm:
    description: farm
    usage: /<command>
    
  nbt:
    description: NBT测试命令
    usage: /<command> [info|set|get|remove|compare|create]